"""
VoiceGuard AI — Evidence Report PDF Generator
================================================
Creates a tamper-proof PDF evidence report suitable for forwarding to
a Cyber Crime portal.

The report contains:
  1. Header with VoiceGuard branding + report ID
  2. Timestamp and device information
  3. Audio frequency glitch analysis table
  4. Acoustic verification results
  5. Location (if available)
  6. Digital signature block (HMAC-SHA256 of the report contents)

The PDF is generated with ReportLab and saved to /reports/<report_id>.pdf.
A hex-encoded HMAC-SHA256 signature is embedded in the PDF and also
stored in MongoDB so the report can be independently verified later.
"""

import hashlib
import hmac
import os
import secrets
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable,
)

from config.settings import settings


def _generate_report_id() -> str:
    """Human-readable unique report ID: RPT-YYYYMMDD-XXXXXX."""
    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    rand = secrets.token_hex(3).upper()
    return f"RPT-{date_str}-{rand}"


def _compute_signature(report_data: dict) -> str:
    """
    Compute an HMAC-SHA256 over the canonical report data.

    The signature proves the report was generated by VoiceGuard and has
    not been tampered with.  Verification: re-compute the HMAC over the
    same fields and compare.
    """
    # Canonical string — sorted keys, deterministic order
    canonical_parts = [
        f"{k}={report_data[k]}"
        for k in sorted(report_data.keys())
        if k != "digital_signature"
    ]
    canonical = "|".join(canonical_parts)
    sig = hmac.new(
        settings.REPORT_SIGNING_KEY.encode(),
        canonical.encode(),
        hashlib.sha256,
    )
    return sig.hexdigest()


def generate_evidence_pdf(report_data: dict, output_dir: str = "reports") -> dict:
    """
    Generate the evidence PDF and return metadata including the digital
    signature and file path.

    Args:
        report_data: dict with keys matching the EvidenceReportCreate schema
                     plus scan_session_id, verdict, max_risk_score, etc.
        output_dir: directory to save the PDF (created if missing)

    Returns:
        {report_id, pdf_path, digital_signature, created_at}
    """
    report_id = _generate_report_id()
    os.makedirs(output_dir, exist_ok=True)
    pdf_path = os.path.join(output_dir, f"{report_id}.pdf")

    # Build the canonical data for signing
    sign_data = {
        "report_id": report_id,
        "scan_session_id": report_data.get("scan_session_id", ""),
        "verdict": report_data.get("verdict", ""),
        "max_risk_score": str(report_data.get("max_risk_score", 0)),
        "total_chunks": str(report_data.get("total_chunks", 0)),
        "issuer": settings.REPORT_ISSUER,
    }
    signature = _compute_signature(sign_data)

    # --- Build the PDF ---
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "VgTitle", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#0a1118"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "VgSub", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#6a7a8a"),
        spaceAfter=12,
    )
    section_style = ParagraphStyle(
        "VgSection", parent=styles["Heading2"],
        fontSize=12, textColor=colors.HexColor("#0066cc"),
        spaceBefore=12, spaceAfter=6,
    )
    body_style = styles["Normal"]

    story = []

    # --- Header ---
    story.append(Paragraph("VoiceGuard AI — Evidence Report", title_style))
    story.append(Paragraph(
        f"Report ID: {report_id} &nbsp;|&nbsp; Issued by: {settings.REPORT_ISSUER} &nbsp;|&nbsp; "
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        subtitle_style,
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a2a3a")))
    story.append(Spacer(1, 8))

    # --- Verdict banner ---
    verdict = report_data.get("verdict", "inconclusive")
    verdict_color = colors.HexColor("#cc2244") if verdict == "deepfake" else colors.HexColor("#00aa44")
    verdict_table = Table(
        [["DETECTION VERDICT", verdict.upper()]],
        colWidths=[60 * mm, 110 * mm],
    )
    verdict_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#0e1620")),
        ("BACKGROUND", (1, 0), (1, 0), verdict_color),
        ("TEXTCOLOR", (0, 0), (0, 0), colors.white),
        ("TEXTCOLOR", (1, 0), (1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 12),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (1, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(verdict_table)
    story.append(Spacer(1, 12))

    # --- Summary metrics ---
    story.append(Paragraph("Detection Summary", section_style))
    summary_data = [
        ["Max Risk Score", f"{report_data.get('max_risk_score', 0):.1f}%"],
        ["Total Chunks Analyzed", str(report_data.get("total_chunks", 0))],
        ["Session ID", report_data.get("scan_session_id", "N/A")],
    ]
    summary_table = Table(summary_data, colWidths=[60 * mm, 110 * mm])
    summary_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1a2a3a")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # --- Device information ---
    story.append(Paragraph("Device Information", section_style))
    dev = report_data.get("device_info", {})
    device_data = [
        ["Device Model", dev.get("model", "N/A")],
        ["OS Version", dev.get("os_version", "N/A")],
        ["App Version", dev.get("app_version", "N/A")],
        ["Device ID", dev.get("device_id", "N/A")],
    ]
    device_table = Table(device_data, colWidths=[60 * mm, 110 * mm])
    device_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1a2a3a")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(device_table)
    story.append(Spacer(1, 10))

    # --- Acoustic verification / glitch analysis ---
    story.append(Paragraph("Active Acoustic Verification — Glitch Analysis", section_style))
    av = report_data.get("acoustic_verification", {})
    av_data = [
        ["Verification Triggered", "YES" if av.get("triggered") else "NO"],
        ["Glitch Count", str(av.get("glitch_count", 0))],
        ["Glitch Severity", f"{av.get('glitch_severity', 0):.3f}"],
    ]
    av_table = Table(av_data, colWidths=[60 * mm, 110 * mm])
    av_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1a2a3a")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(av_table)

    # Per-glitch detail table
    glitch_metrics = av.get("glitch_metrics", [])
    if glitch_metrics:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Per-Glitch Frequency Analysis:", body_style))
        glitch_rows = [["#", "Frequency (Hz)", "Amplitude", "Timestamp (ms)"]]
        for i, gm in enumerate(glitch_metrics, 1):
            glitch_rows.append([
                str(i),
                f"{gm.get('frequency_hz', 0):.1f}",
                f"{gm.get('glitch_amplitude', 0):.3f}",
                str(gm.get("timestamp_ms", 0)),
            ])
        glitch_table = Table(glitch_rows, colWidths=[15 * mm, 50 * mm, 45 * mm, 60 * mm])
        glitch_table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1a2a3a")),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0e1620")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(glitch_table)
    story.append(Spacer(1, 10))

    # --- Location ---
    loc = report_data.get("location")
    if loc and loc.get("latitude") is not None:
        story.append(Paragraph("Location (at time of detection)", section_style))
        loc_data = [
            ["Latitude", f"{loc['latitude']:.6f}"],
            ["Longitude", f"{loc['longitude']:.6f}"],
            ["Accuracy", f"±{loc.get('accuracy_m', 'N/A')} m"],
        ]
        loc_table = Table(loc_data, colWidths=[60 * mm, 110 * mm])
        loc_table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1a2a3a")),
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(loc_table)
        story.append(Spacer(1, 10))

    # --- Digital signature block ---
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a2a3a")))
    story.append(Spacer(1, 8))
    story.append(Paragraph("Digital Signature & Verification", section_style))
    story.append(Paragraph(
        "This report is cryptographically signed using HMAC-SHA256. "
        "The signature below binds the report ID, session, verdict, and "
        "issuer identity.  To verify, re-compute the HMAC over the same "
        "canonical fields using the VoiceGuard verification key.",
        body_style,
    ))
    story.append(Spacer(1, 6))
    sig_data = [
        ["Report ID", report_id],
        ["Issuer", settings.REPORT_ISSUER],
        ["Issuer ID", settings.REPORT_ISSUER_ID],
        ["Algorithm", "HMAC-SHA256"],
        ["Signature (hex)", signature],
    ]
    sig_table = Table(sig_data, colWidths=[40 * mm, 130 * mm])
    sig_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1a2a3a")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("FONTNAME", (1, 4), (1, 4), "Courier"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(sig_table)
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "This report is generated automatically by VoiceGuard AI and is "
        "intended for submission to the National Cyber Crime Reporting Portal. "
        "Tampering with this document invalidates the digital signature.",
        ParagraphStyle("Footer", parent=body_style, fontSize=7, textColor=colors.HexColor("#6a7a8a")),
    ))

    doc.build(story)

    return {
        "report_id": report_id,
        "pdf_path": pdf_path,
        "digital_signature": signature,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
